# Generated by Django 4.2.6 on 2023-10-27 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donante',
            name='Correo_Electronico',
        ),
    ]
