# Generated by Django 4.2.6 on 2023-10-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donantes', '0002_remove_donante_correo_electronico'),
    ]

    operations = [
        migrations.AddField(
            model_name='donante',
            name='Correo_Electrónico',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
