# Generated by Django 4.2.6 on 2023-10-27 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('ID_Beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Dirección', models.CharField(max_length=200)),
                ('Ciudad', models.CharField(max_length=100)),
                ('Teléfono', models.CharField(max_length=20)),
                ('Nivel_de_Pobreza', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10)),
                ('Correo_Electrónico', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='donacion',
            name='ID_Donante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Donaciones.donante'),
        ),
    ]
