# Generated by Django 4.2.6 on 2023-10-31 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donaciones', '0002_donante_donacion_id_donante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='ID_Donante',
        ),
        migrations.DeleteModel(
            name='Donante',
        ),
    ]
