# Generated by Django 4.2.6 on 2023-10-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('ID_Beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Dirección', models.CharField(max_length=200)),
                ('Ciudad', models.CharField(max_length=100)),
                ('Teléfono', models.CharField(max_length=20)),
                ('Correo_Electronico', models.EmailField(max_length=254)),
                ('Nivel_de_Pobreza', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10)),
            ],
        ),
    ]
