# Generated by Django 4.2.6 on 2023-10-27 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='Correo_Electronico',
        ),
    ]
