# Generated by Django 4.2.6 on 2023-10-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beneficiarios', '0002_remove_beneficiario_correo_electronico'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='Correo_Electrónico',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
